name: Codecov Coverage
on: [push]
jobs:
  report-test-coverage:
    name: Report test coverage on push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Generate coverage report
        run: |
          yarn --frozen-lockfile
          yarn test-coverage

      - name: Upload coverage for Web package
        if: success()
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: packages/web/coverage/coverage-final.json
          flags: web

      - name: Upload coverage for Mobile package
        if: success()
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: packages/mobile/coverage/coverage-final.json
          flags: mobile
